name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: ['21.0.2']
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name : Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name : Execute build
        run: ./gradlew --info --stacktrace build